require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NavgationsController do

  # This should return the minimal set of attributes required to create a valid
  # Navgation. As you add validations to Navgation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "app_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NavgationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all navgations as @navgations" do
      navgation = Navgation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:navgations).should eq([navgation])
    end
  end

  describe "GET show" do
    it "assigns the requested navgation as @navgation" do
      navgation = Navgation.create! valid_attributes
      get :show, {:id => navgation.to_param}, valid_session
      assigns(:navgation).should eq(navgation)
    end
  end

  describe "GET new" do
    it "assigns a new navgation as @navgation" do
      get :new, {}, valid_session
      assigns(:navgation).should be_a_new(Navgation)
    end
  end

  describe "GET edit" do
    it "assigns the requested navgation as @navgation" do
      navgation = Navgation.create! valid_attributes
      get :edit, {:id => navgation.to_param}, valid_session
      assigns(:navgation).should eq(navgation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Navgation" do
        expect {
          post :create, {:navgation => valid_attributes}, valid_session
        }.to change(Navgation, :count).by(1)
      end

      it "assigns a newly created navgation as @navgation" do
        post :create, {:navgation => valid_attributes}, valid_session
        assigns(:navgation).should be_a(Navgation)
        assigns(:navgation).should be_persisted
      end

      it "redirects to the created navgation" do
        post :create, {:navgation => valid_attributes}, valid_session
        response.should redirect_to(Navgation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved navgation as @navgation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Navgation.any_instance.stub(:save).and_return(false)
        post :create, {:navgation => { "app_id" => "invalid value" }}, valid_session
        assigns(:navgation).should be_a_new(Navgation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Navgation.any_instance.stub(:save).and_return(false)
        post :create, {:navgation => { "app_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested navgation" do
        navgation = Navgation.create! valid_attributes
        # Assuming there are no other navgations in the database, this
        # specifies that the Navgation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Navgation.any_instance.should_receive(:update).with({ "app_id" => "1" })
        put :update, {:id => navgation.to_param, :navgation => { "app_id" => "1" }}, valid_session
      end

      it "assigns the requested navgation as @navgation" do
        navgation = Navgation.create! valid_attributes
        put :update, {:id => navgation.to_param, :navgation => valid_attributes}, valid_session
        assigns(:navgation).should eq(navgation)
      end

      it "redirects to the navgation" do
        navgation = Navgation.create! valid_attributes
        put :update, {:id => navgation.to_param, :navgation => valid_attributes}, valid_session
        response.should redirect_to(navgation)
      end
    end

    describe "with invalid params" do
      it "assigns the navgation as @navgation" do
        navgation = Navgation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Navgation.any_instance.stub(:save).and_return(false)
        put :update, {:id => navgation.to_param, :navgation => { "app_id" => "invalid value" }}, valid_session
        assigns(:navgation).should eq(navgation)
      end

      it "re-renders the 'edit' template" do
        navgation = Navgation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Navgation.any_instance.stub(:save).and_return(false)
        put :update, {:id => navgation.to_param, :navgation => { "app_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested navgation" do
      navgation = Navgation.create! valid_attributes
      expect {
        delete :destroy, {:id => navgation.to_param}, valid_session
      }.to change(Navgation, :count).by(-1)
    end

    it "redirects to the navgations list" do
      navgation = Navgation.create! valid_attributes
      delete :destroy, {:id => navgation.to_param}, valid_session
      response.should redirect_to(navgations_url)
    end
  end

end
